package RecursiveDescentCompiler;

public enum TokenType
{
    NUMBER, OPERATOR, ID, KEYWORD, UNKNOWN, EOF, BEGIN, WAIT, HALT, 
    ADD, SUB, MPY, DIV, POW, MOD, PUSH, POP, STO, COPY, RVALUE, LVALUE,
    ASSIGNMENT,BLANK, TAB, NULLSTRING, LEFT_PAREN, RIGHT_PAREN, SEMICOLON, NEWLINE

}